version: "3.1"

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress

  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080

  webserver:
    image: wordpress
    restart: always
    ports:
     - 8888:80
    volumes:
     - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
    - db
    - adminer

volumes:
  wordpress_data:
  mysql_data:
