name: Terraform CI/CD


on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout.
    - uses: actions/checkout@v1

    # Update
    - name: Install terraform
      working-directory: /tmp
      run: |
         terraform --version
         whereis terraform
      
        
         
         
         
    
      
