name: Terraform CI/CD


on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout.
    - uses: actions/checkout@v1

    # Update
    - name: Install terraform
      working-directory: /tmp
      run: |
         terraform --version
         whereis terraform
         sudo rm -rf /usr/local/bin/terraform
         sudo wget --quiet https://releases.hashicorp.com/terraform/0.12.12/terraform_0.12.12_linux_amd64.zip 
         sudo unzip terraform_0.12.12_linux_amd64.zip
         sudo mv terraform /usr/bin 
         sudo rm terraform_0.12.12_linux_amd64.zip
         terraform --version
      
        
         
         
         
    
      
